// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl4dnuukuJvSaSlL0RS9jby5rs5VshUZ0',
    appId: '1:1092243595874:android:7d44abcadfc6a0c9a8673b',
    messagingSenderId: '1092243595874',
    projectId: 'mentaliq-app',
    storageBucket: 'mentaliq-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ7IQu69bwDE2yjpgTanI621uL6xwZkAA',
    appId: '1:1092243595874:ios:50fa29c6eea45b29a8673b',
    messagingSenderId: '1092243595874',
    projectId: 'mentaliq-app',
    storageBucket: 'mentaliq-app.firebasestorage.app',
    iosBundleId: 'com.mentaliq.mentaliq',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ZZr4GmWCrnWZklhegiMDArud8unN630',
    appId: '1:1092243595874:web:7d129937790ae855a8673b',
    messagingSenderId: '1092243595874',
    projectId: 'mentaliq-app',
    authDomain: 'mentaliq-app.firebaseapp.com',
    storageBucket: 'mentaliq-app.firebasestorage.app',
  );

}